# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Boyang's Website
subtitle: ''
description: Boyang Li's personal website
author: Boyang Li
language: en
timezone: Europe/London

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://boyangli.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map: 
tag_map: 

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
plugins: hexo-generate-feed
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/Boyang--Li/boyang--li.github.io

# Local Search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

theme_config:
  # ---------------------------------------------------------------
  # Theme Core Configuration Settings
  # See: https://theme-next.org/docs/theme-settings/
  # ---------------------------------------------------------------

  # ---------------------------------------------------------------
  # Theme Core Configuration Settings
  # ---------------------------------------------------------------

  # If false, merge configs from `_data/next.yml` into default configuration (rewrite).
  # If true, will fully override default configuration by options from `_data/next.yml` (override). Only for NexT settings.
  # And if true, all config from default NexT `_config.yml` must be copied into `next.yml`. Use if you know what you are doing.
  # Useful if you want to comment some options from NexT `_config.yml` by `next.yml` without editing default config.
  override: false

  # ---------------------------------------------------------------
  # Site Information Settings
  # ---------------------------------------------------------------

  # To get or check favicons visit: https://realfavicongenerator.net
  # Put your favicons into `hexo-site/source/` (recommend) or `hexo-site/themes/next/source/images/` directory.

  # Default NexT favicons placed in `hexo-site/themes/next/source/images/` directory.
  # And if you want to place your icons in `hexo-site/source/` root directory, you must remove `/images` prefix from pathes.

  # For example, you put your favicons into `hexo-site/source/images` directory.
  # Then need to rename & redefine they on any other names, otherwise icons from Next will rewrite your custom icons in Hexo.
  favicon:
    small: /images/favicon-16x16.png
    medium: /images/favicon-32x32.png
    apple_touch_icon: /images/apple-touch-icon-next.png
    safari_pinned_tab: /images/logo.svg

  footer:
    # Specify the date when the site was setup.
    # If not defined, current year will be used.
    since: 2015

    # Icon between year and copyright info.
    icon:
      # Icon name in fontawesome, see: https://fontawesome.com/v4.7.0/icons
      # `heart` is recommended with animation in red (#ff0000).
      name: heart
      # If you want to animate the icon, set it to true.
      animated: true
      # Change the color of icon, using Hex Code.
      color: "#ff0000"

  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  # When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash from link value (/archives -> archives).
  # Usage: `Key: /link/ || icon`
  # Key is the name of menu item. If translate for this menu will find in languages - this translate will be loaded; if not - Key name will be used. Key is case-senstive.
  # Value before `||` delimeter is the target link.
  # Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, question icon will be loaded.
  menu:
    home: / || home
    project: /categories/project/ || flask
    travel: /categories/travel/ || map-marker
    reading: /categories/reading/ || book
    #tags: /tags/ || tags
    #categories: /categories/ || th
    archives: /archives/ || archive
    about: /about/ || user
    #schedule: /schedule/ || calendar
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat

  # Enable/Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: true

  # ---------------------------------------------------------------
  # Scheme Settings
  # ---------------------------------------------------------------

  # Schemes
  scheme: Mist

  # ---------------------------------------------------------------
  # Sidebar Settings
  # ---------------------------------------------------------------

  sidebar:
    position: right

    # Sidebar Display, available value (only for Muse | Mist):
    #  - post    expand on posts automatically. Default.
    #  - always  expand for all pages automatically
    #  - hide    expand only when click on the sidebar toggle icon.
    #  - remove  Totally remove sidebar including sidebar toggle.
    display: post

  # Sidebar Avatar
  avatar:
    url: /images/avatar1.png

  # Social Links.
  # Usage: `Key: permalink || icon`
  # Key is the link label showing to end users.
  # Value before `||` delimeter is the target permalink.
  # Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, globe icon will be loaded.
  social:
    GitHub: https://github.com/boyang--li || github
    E-Mail: mailto:lbynwpu@gmail.com || envelope
    Linkedin: https://www.linkedin.com/in/boyang-li-10398480 || linkedin

  links:
    PolyU HTML Group: https://www.polyu.edu.hk/researchgrp/cywen/index.php/en/index.html
    Soft Systems Group: https://softsystemsgroup.com/

  # ---------------------------------------------------------------
  # Misc Theme Settings
  # ---------------------------------------------------------------

  # Reduce padding / margin indents on devices with narrow width.
  mobile_layout_economy: true

  # Android Chrome header panel color ($brand-bg / $headband-bg => $black-deep).
  android_chrome_color: "#222"

  # Custom Logo.
  custom_logo:
    enabled: true
    image: /images/avatar1.png

  # ---------------------------------------------------------------
  # Third Party Services Settings
  # ---------------------------------------------------------------

  # Math Formulas Render Support
  math:
    # Default (true) will load mathjax / katex script on demand.
    # That is it only render those page which has `mathjax: true` in Front-matter.
    # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
    per_page: true

    # hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
    mathjax:
      enable: true
      # See: https://mhchem.github.io/MathJax-mhchem/
      mhchem: false

    # hexo-renderer-markdown-it-plus (or hexo-renderer-markdown-it with markdown-it-katex plugin) required for full Katex support.
    katex:
      enable: false
      # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
      copy_tex: false

  # Google Analytics
  google_analytics:
  tracking_id: UA-69834901-1
  # By default, NexT will load an external gtag.js script on your site.
  # If you only need the pageview feature, set the following option to true to get a better performance.
  only_pageview: false

  # Show Views/Visitors of the website/page with busuanzi.
  # Get more information on http://ibruce.info/2015/04/04/busuanzi
  busuanzi_count:
    enable: true
    total_visitors: true
    total_visitors_icon: user
    total_views: true
    total_views_icon: eye
    post_views: true
    post_views_icon: eye

  # Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO
  baidu_push: true

  # Post wordcount display settings
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  symbols_count_time:
  separated_meta: false
  item_text_post: false
  item_text_total: false
  
  # Google Webmaster tools verification.
  # See: https://www.google.com/webmasters
  google_site_verification: google-site-verification=4x3RZgO9V-lMYJccZCB_ReDl8kbX92upSxb6n7oOOnY
  
  # ---------------------------------------------------------------
  # Animation Settings
  # ---------------------------------------------------------------

  # Use velocity to animate everything.
  # For more information: http://velocityjs.org
  motion:
    enable: false
    async: false
    transition:
      # Transition variants:
      # fadeIn | flipXIn | flipYIn | flipBounceXIn | flipBounceYIn
      # swoopIn | whirlIn | shrinkIn | expandIn
      # bounceIn | bounceUpIn | bounceDownIn | bounceLeftIn | bounceRightIn
      # slideUpIn | slideDownIn | slideLeftIn | slideRightIn
      # slideUpBigIn | slideDownBigIn | slideLeftBigIn | slideRightBigIn
      # perspectiveUpIn | perspectiveDownIn | perspectiveLeftIn | perspectiveRightIn
      post_block: fadeIn
      post_header: slideDownIn
      post_body: slideDownIn
      coll_header: slideLeftIn
      # Only for Pisces | Gemini.
      sidebar: slideUpIn